### ISSUE TITLE
unit tests fail on urllib 3 decoding 

### ISSUE THREAD

**Issue by stijnvanhoey** [fluves/pywaterinfo#1]
When running the current unit tests of `draft-package` branch, some of the tests fail:

- `test_waterinfo.py::TestPeriodDates::test_utc_return`
- `test_waterinfo.py::TestTimeseriesValues::test_multiple_ids`

The error says:

```
E           urllib3.exceptions.DecodeError: ('Received response with content-encoding: gzip, but failed to decode it.', error('Error -3 while decompressing data: incorrect header check'))

../../miniconda3/lib/python3.7/site-packages/urllib3/response.py:394: DecodeError

```

Note: current dev-environment not yet properly documented, basically:
- create environmnent (however you like it, conda, pipenv, virtualenv)
- install dev dependencies  `pip install -e .[develop]` and package itself
- configure the pre-commit hooks: `  pip install pre-commit` and   `pre-commit install`
- run the tests: `python setup.py test`

**Comment by johanvdw** [comment]
This is in the first place a server problem (or more accurately, probably a reverse proxy error - netscaler).
according to its headers, the server is sending a gzipped message, while the actual body of the message is not gzipped:
This are the response headers
`{'Age': '1659', 'Date': 'Fri, 10 Apr 2020 21:03:33 GMT', 'Expires': 'Fri, 10 Apr 2020 22:03:34 GMT', 'Cache-Control': 'no-cache', 'Content-Length': '10332', 'Connection': 'Keep-Alive', 'Via': 'NS-CACHE-10.0:   5', 'Server': 'Apache CALC01', 'X-Frame-Options': 'SAMEORIGIN', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Credentials': 'false', 'Content-Encoding': 'gzip', 'Last-Modified': 'Fri, 10 Apr 2020 21:03:34 GMT', 'Content-Type': 'application/json;charset=UTF-8', 'Keep-Alive': 'timeout=5, max=100'}
`
and this is the message (as bytes)

`b'<!doctype html><html lang="en"><head><title>HTTP Status 500 \xe2\x80\x93 Internal Server Error</title><style type="t...ck trace of the root cause is available in the server logs.</p><hr class="line" /><h3>Apache Tomcat</h3></body></html>'`

I believe the exception correctly identifies this situation

**Comment by stijnvanhoey** [comment]
Thanks a lot for the check. The issue exists by two 'returnfields' described by the API, i.e. `AV Quality Code Color` and `RV Quality Code Color`, that induce the decoding issue. As I assume most users won't be interested in these fields, I do think my quick fix of ignoring these will do the job (unit tests are passing).
